// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

type Aluno struct {
	Codigo int32
	Nome   string
}

type Curso struct {
	Codigo    int32
	Descricao string
	Ementa    string
}

type CursoAluno struct {
	Codigo      int32
	CodigoAluno int32
	CodigoCurso int32
}
