// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Aluno struct {
	Codigo int32
	Nome   pgtype.Text
}

type Curso struct {
	ID        uuid.UUID
	Descricao string
	Ementa    string
}

type CursoAluno struct {
	Codigo      int32
	CodigoAluno int32
	CodigoCurso uuid.UUID
}
